### ISSUE TITLE
Remove dist folder from production

### ISSUE THREAD

**Issue by lcor-io** [tanohzana/reacli#18]
**Is your feature request related to a problem? Please describe.**
As @[grabantot](/grabantot) suggested, the dist folder should not appear in produciton. A post install hook could be used to build the CLI.

**Describe the solution you'd like**
Add the dist directory to the .gitignore and change the package.json like this: 
`"scripts": {
 "build": "babel ....",
 "postinstall": "npm run build",`

**Comment by gdarchen** [comment]
By resolving this issue and modifying the `package.json`, it could also be a good idea to set Jest as a `devDependency` 😉

**Comment by tanohzana** [comment]
I think that what should not be pushed to git are binary files. Here we have no binary. Only a transpiled file.
Then, if you want to remove dist, then you have to add a postinstall script, which @gdarchen is working on but rimraf is not usable when not installed glbally. So the question here is: do people need the transpiled JS or they can just use our ES6+ way of writing code... 

TODO:
* Test that executing ./bin/reacli.js works, rather than ./dist/bin/reacli.js

If it does, then no need to use babel I think...
